import type { Metadata } from 'next'

import type { LayoutProps } from '@/shared/types/layout'

import './globals.css'

export const metadata: Metadata = {
  title: 'Chat bot manager',
  description: 'Generated by create next app',
};

export default function RootLayout(props: Readonly<LayoutProps>) {
  return (
    <html lang='en' className='bg-gscale-500 antialiased'>
      <body>{props.children}</body>
    </html>
  );
}
