import type { Metadata } from 'next'
import axios from 'axios'

import type { LayoutProps } from '@/shared/types/layout'

import './globals.css'

export const metadata: Metadata = {
  title: 'Chat bot manager',
  description: 'Generated by create next app',
};

export default function RootLayout(props: Readonly<LayoutProps>) {

  setInterval(async () => {
    await axios.get('https://chatbot-backend-w1ta.onrender.com/health')
  }, 40000)

  return (
    <html lang='en' className='bg-gscale-500 antialiased'>
      <body>{props.children}</body>
    </html>
  );
}
